Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOErrorTraceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
Traceback (most recent call last):
  File "textMining_hash.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_hash.py", line 233, in run
    model_hash = Settings(data_src, 'hash',isYes_label,target_class)
  File "textMining_hash.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_hash.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/androidd.txt'
