Traceback (most recent call last):
  File "textMining.py", line 294, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining.py", line 249, in run
    avg_evaluation, score = cross_val(pd_data, learner, target_class, goal, isWhat)
  File "textMining.py", line 194, in cross_val
    train_pd = smote(train_pd, k, up_to_num).run()
  File "/home/wfu/Github/SMOTE/src/smote.py", line 88, in run
    return pd.DataFrame(total_data)
  File "/share3/wfu/miniconda/lib/python2.7/site-packages/pandas/core/frame.py", line 265, in __init__
    arrays, columns = _to_arrays(data, columns, dtype=dtype)
  File "/share3/wfu/miniconda/lib/python2.7/site-packages/pandas/core/frame.py", line 5279, in _to_arrays
    dtype=dtype)
  File "/share3/wfu/miniconda/lib/python2.7/site-packages/pandas/core/frame.py", line 5360, in _list_to_arrays
    content = list(lib.to_object_array(data).T)
  File "pandas/src/inference.pyx", line 1091, in pandas.lib.to_object_array (pandas/lib.c:62966)
MemoryError
[proxy:0:0@n3l2-14] HYD_pmcd_pmip_control_cmd_cb (./pm/pmiserv/pmip_cb.c:928): assert (!closed) failed
[proxy:0:0@n3l2-14] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:0@n3l2-14] main (./pm/pmiserv/pmip.c:226): demux engine error waiting for event
[mpiexec@n3l2-14] HYDT_bscu_wait_for_completion (./tools/bootstrap/utils/bscu_wait.c:70): one of the processes terminated badly; aborting
[mpiexec@n3l2-14] HYDT_bsci_wait_for_completion (./tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[mpiexec@n3l2-14] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:191): launcher returned error waiting for completion
[mpiexec@n3l2-14] main (./ui/mpich/mpiexec.c:405): process manager error waiting for completion
