Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
  File "<string>", line 1, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
Traceback (most recent call last):
  File "textMining_LinearSVC.py", line 291, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "textMining_LinearSVC.py", line 232, in run
    model_tfidf = Settings(data_src, 'tfidf', isYes_label, target_class)
  File "textMining_LinearSVC.py", line 27, in __init__
    self.corpus = self.load_data()
  File "textMining_LinearSVC.py", line 54, in load_data
    with open(self.data_src, 'r') as f:
IOError: [Errno 2] No such file or directory: '/share3/wfu/Datasets/StackExchange/rupal.txt'
